version: "1.0"
services:

  node_red_vue:
    build: .

    networks:
      - node_red_vue

    ports:
      - "1880:1880"
      - "3000:3000"

    environment:
      DB_USER: root
      DB_PASS: pass
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: demo
      DEV_ENV: "true"
      TZ: "Europe/Copenhagen"
      # Fortæller node-red editoren hvilket flow.json den skal åbne og arbejde i
      FLOWS: "/data/flows.json"
      SFTP_PASS: ${SFTP_PASS}
      BACKEND_URL: http://localhost:1880
      VUE_PORT: 3000
      OS2IOT_API_KEY: ${OS2IOT_API_KEY}

    # Bind mount fra codespace til den kørende containers /data.
    # Det gør det muligt at comitte ændringer i flows til repositoriet
    volumes:
      - "./node-red/:/data" 
      
    depends_on: 
      db:
        condition: service_healthy

  db:
    image: mariadb:10.6.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: demo
      TZ: "Europe/Copenhagen"
    command: [
        '--wait_timeout=60'
    ]
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=pass
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

    networks:
      - node_red_vue
      
networks: 
  node_red_vue:
    name: node_red_vue
